### ISSUE TITLE
Error with numpy random

### ISSUE THREAD

**Issue by sufrjo** [VincentK1991/BERT_summarization_1#2]
Whenever I run the GPT2_preprocessing.py I get this error:

Traceback (most recent call last):
  File "GPT2_preprocessing.py", line 140, in <module>
    main(parser.parse_args())
  File "GPT2_preprocessing.py", line 113, in main
    word_tuple = load_words(df, index)
  File "GPT2_preprocessing.py", line 46, in load_words
    list_len = np.sort(np.random.choice(
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

Any idea why I get this? Help is appreciated

**Comment by VincentK1991** [comment]
I was able to replicate the error.
this is numpy.random.choice receives empty list.
try running
np.random.choice([]) you will see the error.

It seems that the data that you use does not have any keyword or something weird about the data, and therefore you pass empy list to numpy.

**Comment by sufrjo** [comment]
Yeah I figured but I asked because was just trying to run it on the same dataset from kaggle, I'll add a catch to see whats happening. I'll let you know, Thanks
